// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnTheRanj.Infrastructure.Data;

#nullable disable

namespace OnTheRanj.API.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20251223010623_InitialCreate")]
partial class InitialCreate
{
    /// <inheritdoc />
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

        modelBuilder.Entity("OnTheRanj.Core.Entities.ProjectAssignment", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<int>("CreatedBy")
                    .HasColumnType("INTEGER");

                b.Property<int>("EmployeeId")
                    .HasColumnType("INTEGER");

                b.Property<DateTime?>("EndDate")
                    .HasColumnType("TEXT");

                b.Property<int>("ProjectCodeId")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("StartDate")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("ProjectCodeId");

                b.HasIndex("EmployeeId", "ProjectCodeId");

                b.ToTable("ProjectAssignments", (string)null);

                b.HasData(
                    new
                    {
                        Id = 1,
                        CreatedAt = new DateTime(2025, 12, 23, 1, 6, 22, 873, DateTimeKind.Utc).AddTicks(5430),
                        CreatedBy = 1,
                        EmployeeId = 2,
                        EndDate = new DateTime(2026, 2, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                        ProjectCodeId = 1,
                        StartDate = new DateTime(2025, 11, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                    },
                    new
                    {
                        Id = 2,
                        CreatedAt = new DateTime(2025, 12, 23, 1, 6, 22, 873, DateTimeKind.Utc).AddTicks(5440),
                        CreatedBy = 1,
                        EmployeeId = 2,
                        ProjectCodeId = 3,
                        StartDate = new DateTime(2025, 11, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                    },
                    new
                    {
                        Id = 3,
                        CreatedAt = new DateTime(2025, 12, 23, 1, 6, 22, 873, DateTimeKind.Utc).AddTicks(5440),
                        CreatedBy = 1,
                        EmployeeId = 3,
                        EndDate = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                        ProjectCodeId = 2,
                        StartDate = new DateTime(2025, 11, 23, 0, 0, 0, 0, DateTimeKind.Utc)
                    });
            });

        modelBuilder.Entity("OnTheRanj.Core.Entities.ProjectCode", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("ClientName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<int>("CreatedBy")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsBillable")
                    .HasColumnType("INTEGER");

                b.Property<string>("ProjectName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("Code")
                    .IsUnique();

                b.ToTable("ProjectCodes", (string)null);

                b.HasData(
                    new
                    {
                        Id = 1,
                        ClientName = "TechCorp Ltd",
                        Code = "PROJ001",
                        CreatedAt = new DateTime(2025, 12, 23, 1, 6, 22, 873, DateTimeKind.Utc).AddTicks(5370),
                        CreatedBy = 1,
                        IsBillable = true,
                        ProjectName = "E-Commerce Website",
                        Status = "Active"
                    },
                    new
                    {
                        Id = 2,
                        ClientName = "InnovateSoft",
                        Code = "PROJ002",
                        CreatedAt = new DateTime(2025, 12, 23, 1, 6, 22, 873, DateTimeKind.Utc).AddTicks(5380),
                        CreatedBy = 1,
                        IsBillable = true,
                        ProjectName = "Mobile App Development",
                        Status = "Active"
                    },
                    new
                    {
                        Id = 3,
                        ClientName = "OnTheRanj",
                        Code = "INTERNAL001",
                        CreatedAt = new DateTime(2025, 12, 23, 1, 6, 22, 873, DateTimeKind.Utc).AddTicks(5380),
                        CreatedBy = 1,
                        IsBillable = false,
                        ProjectName = "Internal Training",
                        Status = "Active"
                    });
            });

        modelBuilder.Entity("OnTheRanj.Core.Entities.Timesheet", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("Date")
                    .HasColumnType("TEXT");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<int>("EmployeeId")
                    .HasColumnType("INTEGER");

                b.Property<decimal>("HoursWorked")
                    .HasPrecision(5, 2)
                    .HasColumnType("TEXT");

                b.Property<string>("ManagerComments")
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<int>("ProjectCodeId")
                    .HasColumnType("INTEGER");

                b.Property<DateTime?>("ReviewedAt")
                    .HasColumnType("TEXT");

                b.Property<int?>("ReviewedBy")
                    .HasColumnType("INTEGER");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("ProjectCodeId");

                b.HasIndex("ReviewedBy");

                b.HasIndex("EmployeeId", "ProjectCodeId", "Date")
                    .IsUnique();

                b.ToTable("Timesheets", (string)null);
            });

        modelBuilder.Entity("OnTheRanj.Core.Entities.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<string>("FullName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<bool>("IsActive")
                    .HasColumnType("INTEGER");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("Email")
                    .IsUnique();

                b.ToTable("Users", (string)null);

                b.HasData(
                    new
                    {
                        Id = 1,
                        CreatedAt = new DateTime(2025, 12, 23, 1, 6, 22, 650, DateTimeKind.Utc).AddTicks(7430),
                        Email = "manager@ontheranj.com",
                        FullName = "John Manager",
                        IsActive = true,
                        PasswordHash = "$2a$11$S.MwkTKi1xi.3w/FiubX2O2us5DHStmANy8XSZ7odyvFEd6P0e3J.",
                        Role = "Manager"
                    },
                    new
                    {
                        Id = 2,
                        CreatedAt = new DateTime(2025, 12, 23, 1, 6, 22, 763, DateTimeKind.Utc).AddTicks(1220),
                        Email = "alice@ontheranj.com",
                        FullName = "Alice Employee",
                        IsActive = true,
                        PasswordHash = "$2a$11$U9Y0..8jt.AMn1ioslncm.UNn6Yz25YeDTLknDx1XpmoTt2fTBT76",
                        Role = "Employee"
                    },
                    new
                    {
                        Id = 3,
                        CreatedAt = new DateTime(2025, 12, 23, 1, 6, 22, 873, DateTimeKind.Utc).AddTicks(4980),
                        Email = "bob@ontheranj.com",
                        FullName = "Bob Employee",
                        IsActive = true,
                        PasswordHash = "$2a$11$1Im3stg.91hWRGP98ZZBlOCi0MQCE7UM7xAWi3TsBHnY4FMMblq7y",
                        Role = "Employee"
                    });
            });

        modelBuilder.Entity("OnTheRanj.Core.Entities.ProjectAssignment", b =>
            {
                b.HasOne("OnTheRanj.Core.Entities.User", "Employee")
                    .WithMany("ProjectAssignments")
                    .HasForeignKey("EmployeeId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("OnTheRanj.Core.Entities.ProjectCode", "ProjectCode")
                    .WithMany("ProjectAssignments")
                    .HasForeignKey("ProjectCodeId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Employee");

                b.Navigation("ProjectCode");
            });

        modelBuilder.Entity("OnTheRanj.Core.Entities.Timesheet", b =>
            {
                b.HasOne("OnTheRanj.Core.Entities.User", "Employee")
                    .WithMany("Timesheets")
                    .HasForeignKey("EmployeeId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("OnTheRanj.Core.Entities.ProjectCode", "ProjectCode")
                    .WithMany("Timesheets")
                    .HasForeignKey("ProjectCodeId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("OnTheRanj.Core.Entities.User", "Reviewer")
                    .WithMany()
                    .HasForeignKey("ReviewedBy")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Employee");

                b.Navigation("ProjectCode");

                b.Navigation("Reviewer");
            });

        modelBuilder.Entity("OnTheRanj.Core.Entities.ProjectCode", b =>
            {
                b.Navigation("ProjectAssignments");

                b.Navigation("Timesheets");
            });

        modelBuilder.Entity("OnTheRanj.Core.Entities.User", b =>
            {
                b.Navigation("ProjectAssignments");

                b.Navigation("Timesheets");
            });
#pragma warning restore 612, 618
    }
}
