// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnTheRanj.Infrastructure.Data;

#nullable disable

namespace OnTheRanj.Infrastructure.Migrations;

[DbContext(typeof(ApplicationDbContext))]
partial class ApplicationDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

        modelBuilder.Entity("OnTheRanj.Core.Entities.ProjectAssignment", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<int>("CreatedBy")
                    .HasColumnType("INTEGER");

                b.Property<int>("EmployeeId")
                    .HasColumnType("INTEGER");

                b.Property<DateTime?>("EndDate")
                    .HasColumnType("TEXT");

                b.Property<int>("ProjectCodeId")
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("StartDate")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("ProjectCodeId");

                b.HasIndex("EmployeeId", "ProjectCodeId");

                b.ToTable("ProjectAssignments", (string)null);
            });

        modelBuilder.Entity("OnTheRanj.Core.Entities.ProjectCode", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<string>("ClientName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("TEXT");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<int>("CreatedBy")
                    .HasColumnType("INTEGER");

                b.Property<bool>("IsBillable")
                    .HasColumnType("INTEGER");

                b.Property<string>("ProjectName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("TEXT");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("Code")
                    .IsUnique();

                b.ToTable("ProjectCodes", (string)null);
            });

        modelBuilder.Entity("OnTheRanj.Core.Entities.Timesheet", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<DateTime>("Date")
                    .HasColumnType("TEXT");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<int>("EmployeeId")
                    .HasColumnType("INTEGER");

                b.Property<decimal>("HoursWorked")
                    .HasPrecision(5, 2)
                    .HasColumnType("TEXT");

                b.Property<string>("ManagerComments")
                    .HasMaxLength(500)
                    .HasColumnType("TEXT");

                b.Property<int>("ProjectCodeId")
                    .HasColumnType("INTEGER");

                b.Property<DateTime?>("ReviewedAt")
                    .HasColumnType("TEXT");

                b.Property<int?>("ReviewedBy")
                    .HasColumnType("INTEGER");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("TEXT");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("ProjectCodeId");

                b.HasIndex("ReviewedBy");

                b.HasIndex("EmployeeId", "ProjectCodeId", "Date")
                    .IsUnique();

                b.ToTable("Timesheets", (string)null);
            });

        modelBuilder.Entity("OnTheRanj.Core.Entities.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("TEXT");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<string>("FullName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("TEXT");

                b.Property<bool>("IsActive")
                    .HasColumnType("INTEGER");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("TEXT");

                b.HasKey("Id");

                b.HasIndex("Email")
                    .IsUnique();

                b.ToTable("Users", (string)null);
            });

        modelBuilder.Entity("OnTheRanj.Core.Entities.ProjectAssignment", b =>
            {
                b.HasOne("OnTheRanj.Core.Entities.User", "Employee")
                    .WithMany("ProjectAssignments")
                    .HasForeignKey("EmployeeId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("OnTheRanj.Core.Entities.ProjectCode", "ProjectCode")
                    .WithMany("ProjectAssignments")
                    .HasForeignKey("ProjectCodeId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Employee");

                b.Navigation("ProjectCode");
            });

        modelBuilder.Entity("OnTheRanj.Core.Entities.Timesheet", b =>
            {
                b.HasOne("OnTheRanj.Core.Entities.User", "Employee")
                    .WithMany("Timesheets")
                    .HasForeignKey("EmployeeId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("OnTheRanj.Core.Entities.ProjectCode", "ProjectCode")
                    .WithMany("Timesheets")
                    .HasForeignKey("ProjectCodeId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("OnTheRanj.Core.Entities.User", "Reviewer")
                    .WithMany()
                    .HasForeignKey("ReviewedBy")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Employee");

                b.Navigation("ProjectCode");

                b.Navigation("Reviewer");
            });

        modelBuilder.Entity("OnTheRanj.Core.Entities.ProjectCode", b =>
            {
                b.Navigation("ProjectAssignments");

                b.Navigation("Timesheets");
            });

        modelBuilder.Entity("OnTheRanj.Core.Entities.User", b =>
            {
                b.Navigation("ProjectAssignments");

                b.Navigation("Timesheets");
            });
#pragma warning restore 612, 618
    }
}
